package br.com.correios.webservice.calculador;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

import java.math.BigDecimal;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "CalcPrecoPrazoWSSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface CalcPrecoPrazoWSSoap {


    /**
     * @param nCdEmpresa
     * @param nVlDiametro
     * @param sCdMaoPropria
     * @param sCepDestino
     * @param nCdFormato
     * @param nVlPeso
     * @param nVlLargura
     * @param nVlComprimento
     * @param sCdAvisoRecebimento
     * @param nCdServico
     * @param sCepOrigem
     * @param nVlValorDeclarado
     * @param sDsSenha
     * @param nVlAltura
     * @return returns org.tempuri.CResultado
     */
    @WebMethod(operationName = "CalcPrecoPrazo", action = "http://tempuri.org/CalcPrecoPrazo")
    @WebResult(name = "CalcPrecoPrazoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrecoPrazo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazo")
    @ResponseWrapper(localName = "CalcPrecoPrazoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazoResponse")
    CResultado calcPrecoPrazo(
            @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
                    String nCdEmpresa,
            @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
                    String sDsSenha,
            @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
                    String nCdServico,
            @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
                    String sCepOrigem,
            @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
                    String sCepDestino,
            @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
                    String nVlPeso,
            @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
                    int nCdFormato,
            @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlComprimento,
            @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlAltura,
            @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlLargura,
            @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlDiametro,
            @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
                    String sCdMaoPropria,
            @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlValorDeclarado,
            @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
                    String sCdAvisoRecebimento);

    /**
     * @param nCdEmpresa
     * @param nVlDiametro
     * @param sCdMaoPropria
     * @param sCepDestino
     * @param nCdFormato
     * @param nVlPeso
     * @param nVlLargura
     * @param nVlComprimento
     * @param sCdAvisoRecebimento
     * @param nCdServico
     * @param sCepOrigem
     * @param nVlValorDeclarado
     * @param sDtCalculo
     * @param sDsSenha
     * @param nVlAltura
     * @return returns org.tempuri.CResultado
     */
    @WebMethod(operationName = "CalcPrecoPrazoData", action = "http://tempuri.org/CalcPrecoPrazoData")
    @WebResult(name = "CalcPrecoPrazoDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrecoPrazoData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazoData")
    @ResponseWrapper(localName = "CalcPrecoPrazoDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazoDataResponse")
    CResultado calcPrecoPrazoData(
            @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
                    String nCdEmpresa,
            @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
                    String sDsSenha,
            @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
                    String nCdServico,
            @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
                    String sCepOrigem,
            @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
                    String sCepDestino,
            @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
                    String nVlPeso,
            @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
                    int nCdFormato,
            @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlComprimento,
            @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlAltura,
            @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlLargura,
            @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlDiametro,
            @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
                    String sCdMaoPropria,
            @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlValorDeclarado,
            @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
                    String sCdAvisoRecebimento,
            @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
                    String sDtCalculo);

    /**
     * @param nCdEmpresa
     * @param nVlDiametro
     * @param sCdMaoPropria
     * @param sCepDestino
     * @param nCdFormato
     * @param nVlPeso
     * @param nVlLargura
     * @param nVlComprimento
     * @param sCdAvisoRecebimento
     * @param nCdServico
     * @param sCepOrigem
     * @param nVlValorDeclarado
     * @param sDtCalculo
     * @param sDsSenha
     * @param nVlAltura
     * @return returns org.tempuri.CResultado
     */
    @WebMethod(operationName = "CalcPrecoPrazoRestricao", action = "http://tempuri.org/CalcPrecoPrazoRestricao")
    @WebResult(name = "CalcPrecoPrazoRestricaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrecoPrazoRestricao", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazoRestricao")
    @ResponseWrapper(localName = "CalcPrecoPrazoRestricaoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazoRestricaoResponse")
    CResultado calcPrecoPrazoRestricao(
            @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
                    String nCdEmpresa,
            @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
                    String sDsSenha,
            @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
                    String nCdServico,
            @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
                    String sCepOrigem,
            @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
                    String sCepDestino,
            @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
                    String nVlPeso,
            @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
                    int nCdFormato,
            @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlComprimento,
            @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlAltura,
            @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlLargura,
            @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlDiametro,
            @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
                    String sCdMaoPropria,
            @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlValorDeclarado,
            @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
                    String sCdAvisoRecebimento,
            @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
                    String sDtCalculo);

    /**
     * @param nCdEmpresa
     * @param nVlDiametro
     * @param sCdMaoPropria
     * @param sCepDestino
     * @param nCdFormato
     * @param nVlPeso
     * @param nVlLargura
     * @param nVlComprimento
     * @param sCdAvisoRecebimento
     * @param nCdServico
     * @param sCepOrigem
     * @param nVlValorDeclarado
     * @param sDsSenha
     * @param nVlAltura
     * @return returns org.tempuri.CResultado
     */
    @WebMethod(operationName = "CalcPreco", action = "http://tempuri.org/CalcPreco")
    @WebResult(name = "CalcPrecoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPreco", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPreco")
    @ResponseWrapper(localName = "CalcPrecoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoResponse")
    CResultado calcPreco(
            @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
                    String nCdEmpresa,
            @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
                    String sDsSenha,
            @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
                    String nCdServico,
            @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
                    String sCepOrigem,
            @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
                    String sCepDestino,
            @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
                    String nVlPeso,
            @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
                    int nCdFormato,
            @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlComprimento,
            @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlAltura,
            @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlLargura,
            @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlDiametro,
            @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
                    String sCdMaoPropria,
            @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlValorDeclarado,
            @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
                    String sCdAvisoRecebimento);

    /**
     * @param nCdEmpresa
     * @param nVlDiametro
     * @param sCdMaoPropria
     * @param sCepDestino
     * @param nCdFormato
     * @param nVlPeso
     * @param nVlLargura
     * @param nVlComprimento
     * @param sCdAvisoRecebimento
     * @param nCdServico
     * @param sCepOrigem
     * @param nVlValorDeclarado
     * @param sDtCalculo
     * @param sDsSenha
     * @param nVlAltura
     * @return returns org.tempuri.CResultado
     */
    @WebMethod(operationName = "CalcPrecoData", action = "http://tempuri.org/CalcPrecoData")
    @WebResult(name = "CalcPrecoDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrecoData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoData")
    @ResponseWrapper(localName = "CalcPrecoDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoDataResponse")
    CResultado calcPrecoData(
            @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
                    String nCdEmpresa,
            @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
                    String sDsSenha,
            @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
                    String nCdServico,
            @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
                    String sCepOrigem,
            @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
                    String sCepDestino,
            @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
                    String nVlPeso,
            @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
                    int nCdFormato,
            @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlComprimento,
            @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlAltura,
            @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlLargura,
            @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlDiametro,
            @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
                    String sCdMaoPropria,
            @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
                    BigDecimal nVlValorDeclarado,
            @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
                    String sCdAvisoRecebimento,
            @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
                    String sDtCalculo);

    /**
     * @param nCdServico
     * @param sCepDestino
     * @param sCepOrigem
     * @return returns org.tempuri.CResultado
     */
    @WebMethod(operationName = "CalcPrazo", action = "http://tempuri.org/CalcPrazo")
    @WebResult(name = "CalcPrazoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrazo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrazo")
    @ResponseWrapper(localName = "CalcPrazoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrazoResponse")
    CResultado calcPrazo(
            @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
                    String nCdServico,
            @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
                    String sCepOrigem,
            @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
                    String sCepDestino);

    /**
     * @param nCdServico
     * @param sCepDestino
     * @param sCepOrigem
     * @param sDtCalculo
     * @return returns org.tempuri.CResultado
     */
    @WebMethod(operationName = "CalcPrazoData", action = "http://tempuri.org/CalcPrazoData")
    @WebResult(name = "CalcPrazoDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrazoData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrazoData")
    @ResponseWrapper(localName = "CalcPrazoDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrazoDataResponse")
    CResultado calcPrazoData(
            @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
                    String nCdServico,
            @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
                    String sCepOrigem,
            @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
                    String sCepDestino,
            @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
                    String sDtCalculo);

    /**
     * @param nCdServico
     * @param sCepDestino
     * @param sCepOrigem
     * @param sDtCalculo
     * @return returns org.tempuri.CResultado
     */
    @WebMethod(operationName = "CalcPrazoRestricao", action = "http://tempuri.org/CalcPrazoRestricao")
    @WebResult(name = "CalcPrazoRestricaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrazoRestricao", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrazoRestricao")
    @ResponseWrapper(localName = "CalcPrazoRestricaoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrazoRestricaoResponse")
    CResultado calcPrazoRestricao(
            @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
                    String nCdServico,
            @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
                    String sCepOrigem,
            @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
                    String sCepDestino,
            @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
                    String sDtCalculo);

    /**
     * @param nVlPeso
     * @param strDataCalculo
     * @param nCdServico
     * @return returns org.tempuri.CResultado
     */
    @WebMethod(operationName = "CalcPrecoFAC", action = "http://tempuri.org/CalcPrecoFAC")
    @WebResult(name = "CalcPrecoFACResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrecoFAC", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoFAC")
    @ResponseWrapper(localName = "CalcPrecoFACResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoFACResponse")
    CResultado calcPrecoFAC(
            @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
                    String nCdServico,
            @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
                    String nVlPeso,
            @WebParam(name = "strDataCalculo", targetNamespace = "http://tempuri.org/")
                    String strDataCalculo);

}
